version: "3"
services:
  database:
    image: "postgres:12"
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
      POSTGRES_DB: "hello"
#  app:
#    image: "hello"
#    container_name: "app"
#    ports:
#      - "8181:8080"
volumes:
  data:
